#Plays ambient background sound according to the biome and time of day.
"BiomeAmbience Enabled" = true
#Plays specific ambient sound according to the situation or location.
"SituationalAmbience Enabled" = true

[BiomeAmbience]
	#Affects the volume of all biome ambient sounds. 1.0 is full volume.
	"Volume scaling" = 0.25
	#Number of blocks above the ground that biome ambience will be silenced.
	#Set to zero to disable.
	"Above ground for ambience silencing" = 32
	#Number of blocks to check for neighbouring biomes.
	#Set to zero to disable.
	"Biome sound blending" = 32
	#Dimensions in which biome ambience will be played.
	"Valid dimensions" = ["minecraft:overworld", "minecraft:the_end"]

[Core]
	#The channel that Charmonium will use for playing sounds. Defaults to 'ambient'.
	#Options: music, record, weather, block, hostile, neutral, player, ambient, voice
	"Audio channel" = "ambient"

[SituationalAmbience]
	#Affects the volume of all situational ambient sounds. 1.0 is full volume.
	"Volume scaling" = 0.25
	#Number of blocks above the ground that biome ambience will be silenced.
	#Set to zero to disable.
	"Above ground for ambience silencing" = 32
	#If true, plays ambient sounds while anywhere in the End.
	"Alien ambience" = true
	#If true, plays ambient sounds in cold and/or barren overworld environments.
	"Bleak ambience" = true
	#If true, plays a low drone sound when in a cave below Y 48.
	"Cave drone ambience" = true
	#If true, plays more intense cave sounds when below Y 0 and light level is lower than 10.
	"Cave depth ambience" = true
	#If true, plays ambient sounds when the player is underground and near deepslate blocks.
	"Deepslate ambience" = true
	#If true, plays ambient sounds in dry and/or hot overworld environments.
	"Dry ambience" = true
	#If true, plays ambient sounds from a nearby amethyst geode.
	"Geode ambience" = true
	#If true, plays ambient sounds when the player is underground and near gravel blocks.
	"Gravel ambience" = true
	#If true, plays ambient sounds when high up in the overworld.
	"High ambience" = true
	#If true, plays ambient sounds while inside a woodland mansion.
	"Mansion ambience" = true
	#If true, plays ambient sounds from a nearby mineshaft.
	"Mineshaft ambience" = true
	#If true, plays ambient sounds in plains environments at night.
	"Night plains ambience" = true
	#If true, plays ambient sounds when in a cold biome during a thunderstorm.
	"Snowstorm ambience" = true
	#If true, plays water sounds from a nearby water source when underground.
	"Underground water ambience" = true
	#If true, plays ambient sounds when a player is inside a village.
	"Village ambience" = true
	#Dimensions in which cave drone and cave depth sounds will be played.
	"Valid cave drone dimensions" = ["minecraft:overworld"]

