import crafttweaker.api.tag.MCTag;
<tag:blocks:crafttweaker:veinmine>.add(<block:minecraft:dripstone_block>);
<tag:blocks:crafttweaker:veinmine>.add(<block:minecraft:andesite>);
<tag:blocks:crafttweaker:veinmine>.add(<block:minecraft:diorite>);
<tag:blocks:crafttweaker:veinmine>.add(<block:minecraft:granite>);
<tag:blocks:crafttweaker:veinmine>.add(<block:minecraft:calcite>);
<tag:blocks:crafttweaker:veinmine>.add(<block:create:limestone>);
<tag:blocks:crafttweaker:veinmine>.add(<block:minecraft:glowstone>);
<tag:blocks:crafttweaker:veinmine>.add(<block:minecraft:clay>);
<tag:blocks:minecraft:mineable/pickaxe>.add(<block:minecraft:glowstone>);